from configs.model_configs.LeNet import LeNetConfig
from configs.model_configs.AlexNet import AlexNetConfig
from configs.model_configs.VGG16 import VGG16Config
from configs.model_configs.Inception import InceptionConfig
from configs.model_configs.DenseNet import DenseNetConfig
from configs.model_configs.ResNet import ResNetConfig
from configs.model_configs.Inceptionv2 import Inceptionv2Config
from configs.model_configs.Inceptionv3 import Inceptionv3Config
from configs.model_configs.ResNeXt import ResNeXtConfig
from configs.model_configs.MobileNet import MobileNetConfig
from configs.model_configs.MobileNetv2 import MobileNetv2Config
from configs.model_configs.SENet import SENetConfig
from configs.model_configs.SPPNet import SPPNetConfig
from configs.model_configs.RCNN import RCNNConfig
from configs.model_configs.FastRCNN import Fast_RCNNConfig
from configs.model_configs.ViT import ViTConfig
from configs.model_configs.ConvNeXt import ConvNeXtConfig
from configs.model_configs.DeiT import DeiTConfig
from configs.model_configs.ResNetSB import ResNetSBConfig
from configs.model_configs.T2T_ViT import T2T_ViTConfig