from backbones.AlexNet.model import AlexNet
from backbones.VGG16.model import VGG16
from backbones.InceptionNet.model import Inception
from backbones.DenseNet.model import DenseNet
from backbones.ResNet.model import ResNet
from backbones.InceptionNet_v2.model import Inceptionv2
from backbones.InceptionNet_v3.model import Inceptionv3
from backbones.ResNeXt.model import ResNeXt
from backbones.MobileNet.model import MobileNet