name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser fvcore numpy setuptools einops
          pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          python setup.py sdist bdist_wheel
          pip install .
      - name: Sphinx build
        run: |
          rm -rf docs/build/*
          sphinx-build -b html -v docs/source/ docs/build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
